site_name: Czarna Magia Docs
theme:
    name: material
    language: en
    features:
        - navigation.expand
        - navigation.sections
        - toc.integrate
    palette:
        scheme: slate
nav:
    - Main Page: index.md
    - Projects: Knowledge/Projects/index.md
    - Tutorials: Knowledge/Tutorials/index.md
repo_url: https://github.com/mikitavydrankou/Infinitar
repo_name: Infinitar
